#!/bin/sh /etc/rc.common
#(c) 2010 ivan_wl
START=99

start() {
	service_start /usr/bin/gdut-drcom  -c /etc/gdut-drcom.conf 1> /tmp/gdut-drcom.log  2>/tmp/gdut-drcom_error.log&
}

stop()
{
	service_stop /usr/bin/gdut-drcom
}
