#!/bin/sh /etc/rc.common
#(c) 2010 ivan_wl
START=99

start() {
	remote_ip=$(uci get gdut_drcom.@gdut_drcom[0].remote_ip 2>/dev/null)
	keep_alive1_flag=$(uci get gdut_drcom.@gdut_drcom[0].keep_alive1_flag 2>/dev/null)
	enable=$(uci get gdut_drcom.@gdut_drcom[0].enable 2>/dev/null)
	if [ "$enable"x = "1"x ]; then
		/etc/init.d/gdut-drcom enable
	else
		/etc/init.d/gdut-drcom disable
		return
	fi

	cmd="service_start /usr/bin/gdut-drcom -c /etc/gdut-drcom.conf "
	if [ -n "$remote_ip" ]; then
		cmd=$cmd"--remote-ip=$remote_ip "
	fi
	if [ -n "$keep_alive1_flag" ]; then
		cmd=$cmd"--keep-alive1-flag=$keep_alive1_flag "
	fi
	cmd=$cmd"1> /tmp/gdut-drcom.log 2>/tmp/gdut-drcom_error.log &"

	eval $cmd
}
stop()
{
	service_stop /usr/bin/gdut-drcom
	return 0
}
